name: show_error_handler
description: " A Flutter package that provides a convenient and customizable way to display errors to the user. This package simplifies error handling by providing a centralized mechanism to present error messages, handling different error types gracefully, and offering flexibility in how errors are displayed.  It allows developers to define custom error presenters and easily integrate them into their applications."
version: 0.0.1
homepage: https://weincoder.github.io/show_error_handler/

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_code_linter: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
